### ISSUE TITLE
`GeoInteface.getgeom(polygon, i)` is very slow. We need a cache for calculating holes and rings only once.

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/Shapefile.jl#108]
Using `getgeom(multipolygon)` rather than `getgeom(polygon, i)` is recommended... but in practice the later is used a lot and is currently insanely slow if you have e.g. 100 holes in a polygon.

We could maybe add a cache of bit indices for each polygon with the exterior then all the holes. Then we can just index with it to get each polygon after the first time.

**Comment by asinghvi17** [comment]
I believe this is now a thing.
