### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dapias** [JuliaGeo/Shapefile.jl#16]
May you guys document this package, please?

**Comment by yeesian** [comment]
Will you like to give it a shot? PRs gladly welcome!

**Comment by Hugo-Trentesaux** [comment]
I could document if I understand how it works! But at the moment it's a bit difficult.

**Comment by visr** [comment]
Questions welcome! Right now "how it works" is hardly covered. The [quick start](https://github.com/JuliaGeo/Shapefile.jl#quick-start) is very minimal and could be expanded, but it actually shows most of the functionality that is meant for users of this library.

The "how it works" part could be seen more as developer documentation. For the DBFTables dependency, there was some more complexity, which I wrote down here: https://github.com/JuliaData/DBFTables.jl#implementation-details
