### ISSUE TITLE
DBF support

### ISSUE THREAD

**Issue by cchderrick** [JuliaGeo/Shapefile.jl#19]
I am writing some tests for a simple DBF reader that I want to contribute. Where I encounter a problem with the `test.dbf`, the 3rd record's attribute `TestInt` and `TestDouble` are filled with `*` characters (0x2a). This cause `parse(Int64,"******")` to throw an error.

Not sure if "*" is valid characters for numeric type in DBF spec, or how to handle them? Do I stuff a `nothing` if it fail at parsing?

**Comment by visr** [comment]
Would be great to have support for the full shp/shx/dbf format in this package. Since the dBase file format is also used for other applications, I did a quick check to see if others had already worked on it using [Julia Observer](https://www.juliaobserver.com/searches?utf8=%E2%9C%93&term=DBF).

I see two implementations of readers that already exist:
- https://github.com/JuliaData/DBFTables.jl
- https://github.com/penntaylor/DBaseReader.jl

Not sure which one is better. I would guess `DBFTables` since it returns DataFrames, not DataArrays like the other package. Perhaps one should be deprecated for the other.
But can you have a look if you can make use of this package to add support for DBF to Shapefile.jl? It might need some work though.

Regarding the `***`, this should probably be interpreted as missing data (`Union{Missing, T}`, see [this blog post](https://julialang.org/blog/2018/06/missing). From what I can find online:

https://www.stattransfer.com/support/manual/dBase.html
> dBASE does not directly support missing values.  On input to Stat/Transfer, blanks in an dBASE file are interpreted as missing values.  If a data set is being transferred to an dBASE file format, missing values in the input files are set to blank in the dBASE file.  Blanks are interpreted as zero by dBASE.  Many other programs, including Stat/Transfer, interpret these blanks as missing.

https://www.ibm.com/support/knowledgecenter/SSLVMB_23.0.0/spss/base/syn_save_translate_databases.html
> Numeric variables containing the system-missing value are translated to **** in dBASE III and dBASE IV and 0 in dBASE II.

**Comment by cchderrick** [comment]
Since it seems like my implementation looks very similar to DBFTables.jl (rather than DBaseReader), I will start from there, also it looks like it need some updating as well.

**Comment by cchderrick** [comment]
Regarding the `*`

Taking a hint from the readme in testcase folder, inside `shapelib-1.4.1\tests`, it appears `test3.sh` is the script that made the `test.dbf`
here is the small snippet from the script
```sh
./shpcreate test polygon
./dbfcreate test.dbf -s Description 30 -n TestInt 6 0 -n TestDouble 16 5

./shpadd test 0 0 100 0 100 100 0 100 0 0 + 20 20 20 30 30 30 20 20
./dbfadd test.dbf "Square with triangle missing" 1.5 2.5

./shpadd test 150 150 160 150 180 170 150 150
./dbfadd test.dbf "Smaller triangle" 100 1000.25

./shpadd test 150 150 160 150 180 170 150 150
./dbfadd test.dbf "" "" ""

./shpdump test.shp
./dbfdump test.dbf
```

looks like it is supposed to be missing, but not sure how `""` turns into `"******"`

**Comment by cchderrick** [comment]
I suppose this issue is really out of scoop now.
I updated DBFTables.jl to working conditions for v0.7/v1.0 and handle these parsing problems.

The next step would be integrating DBFTables into this package, but given the maturity of ArchGDAL, it seems that would be an duplicating effort yielding comparable capabilities at best (probably inferior).

**Comment by yeesian** [comment]
> The next step would be integrating DBFTables into this package, but given the maturity of ArchGDAL, it seems that would be an duplicating effort yielding comparable capabilities at best (probably inferior)

There is value in having drivers that are implemented in native Julia code though!

**Comment by cchderrick** [comment]
Currently, dbf files can be read using a seperate package `DBFTables.jl`, it reads DBF file into Dataframe. I have some skeleton [code ](https://github.com/cchderrick/Shapefile.jl/blob/51eea120f8b8884bee233c6476282cc370de0c9e/src/parsefile.jl) that parse the 3 files (`.shp`, `.shx`, `.dbf`) into GeoInterface's Feature collections, I think I got stuck on the `bbox`, `crs` fields, and totally forgot about it.

**Comment by mkborregaard** [comment]
Is that in a public branch so someone could finish and PR it to here?

**Comment by mkborregaard** [comment]
haha just saw that yes it is.

**Comment by mkborregaard** [comment]
What branch is this on?

**Comment by cchderrick** [comment]
[shx_dbf_reading](https://github.com/cchderrick/Shapefile.jl/tree/shx_dbf_reading) branch.
Ignore the word `shx`, I split it out and PR already.

**Comment by meggart** [comment]
What is the status on this? Do you still intend to make a PR for dbf or would it be ok if one of us took your branch and continues? @mkborregaard have you already worked on the branch?

**Comment by cchderrick** [comment]
I don't think I have any capacity to work on it for a long while. I am okay if anyone take the branch.
Reading DBF into dataframe is pretty much done by DBFTables.jl; most of the effort on that branch is wrapping those information into GeoInterface.

**Comment by meggart** [comment]
Ok, thanks for the info. I am currently using DBFTables.jl alongside Shapefile.jl as you suggested. When I have familiarized myself a bit more with GeoInterface, I will see what I can do.

**Comment by mkborregaard** [comment]
I would love if anyone had the energy to do this - I'm only back in the office mid-september.

**Comment by visr** [comment]
I cherry picked @cchderrick's relevant commits and pushed them to the `dbf` branch on this repository.
Though I noticed DBFTables takes a dependency on DataFrames and returns that format. I think it would be better to first update DBFTables to use the Tables interface instead. With that users can still easily create a DataFrame, but also other Tables.

ref https://github.com/JuliaData/DBFTables.jl/issues/8
