### ISSUE TITLE
Rect{T} constructor ordering and read(io,Rect{T}) missmatch?

### ISSUE THREAD

**Issue by cchderrick** [JuliaGeo/Shapefile.jl#24]
Rect struct order: **top**, left, **bottom**, right
Construction order: **miny**, minx, **maxy**, maxx

Should it be: **maxy**, minx, **miny**, maxx ?

https://github.com/JuliaGeo/Shapefile.jl/blob/5ed5dde28dc607eff955e77331151e31ab460e23/src/Shapefile.jl#L5-L10

https://github.com/JuliaGeo/Shapefile.jl/blob/5ed5dde28dc607eff955e77331151e31ab460e23/src/Shapefile.jl#L137-L143

**Comment by visr** [comment]
Oh yes this is a bit of a mess. There were never any tests for this, and I guess many people never used the bounding boxes, only the geometry itself.

What it should be in my view is neither of those two options, but `(minx, miny, maxx, maxy)` which would be more consistent with:

- The order in the shapefiles themselves
- The GeoJSON spec bounding box: https://tools.ietf.org/html/rfc7946#section-5
- And thus also GeoInterface.jl which uses this definition

This would mean changing the `Rect` struct though, which is pretty breaking, but considering this was never correct I guess that's no real issue.
