### ISSUE TITLE
Main read method does not properly handle shapefile spec(mainly null type)

### ISSUE THREAD

**Issue by ndinsmore** [JuliaGeo/Shapefile.jl#27]
I was trying to load the shapefile, [ne_10m_rivers_lake_centerlines.shp](https://github.com/nvkelso/natural-earth-vector/raw/master/10m_physical/ne_10m_rivers_lake_centerlines.shp) from the natural earth, I was getting an EOF error.   
After digging into it the issue was traced to the main read method not handling the null shape type properly it would still go on and try to read it as the shapetype of the rest of the file.  The change below makes the method operate as it should with no appreciable performance hit:
```julia 
function Base.read(io::IO,::Type{Handle})
        code = bswap(read(io,Int32))
        read!(io, Vector{Int32}(undef, 5))
        fileSize = bswap(read(io,Int32))
        version = read(io,Int32)
        file_shapeType = read(io,Int32) #Change to make it persistent to use as reference
        shapeType::Int32=0 #predine shape type
        MBR = read(io,Rect{Float64})
        zmin = read(io,Float64)
        zmax = read(io,Float64)
        mmin = read(io,Float64)
        mmax = read(io,Float64)
        jltype = SHAPETYPE[file_shapeType] #Change persistent variable
        shapes = Vector{jltype}(undef, 0)
        file = Handle(code,fileSize,version,shapeType,MBR,Interval(zmin,zmax),Interval(mmin,mmax),shapes)
        while(!eof(io))
            num = bswap(read(io,Int32))
            rlength = bswap(read(io,Int32))
            shapeType = read(io,Int32)
            (rlength != 2) && (shapeType == file_shapeType ) ?  #ensure record is longer than just type or is right type
                    push!(shapes, read(io, jltype)) : #if not read as normal
                    read(io,2*rlength-4) #otherwise make sure we jump over the rest of the bytes claimed by rlength
        end
        file
    end
```

As a side effect, this will also make the code just gracefully skip over types that aren't the right type for the fie.  

The issue it doesn't address is if ``` rlength``` is longer than the amount of data used by the shape definition, I couldn't determine if the spec allowed for this, but it would be good to protect against it.   It would take a lot more code chang though.

**Comment by visr** [comment]
Hi, thanks for raising this issue. Definitely want this to work on Natural Earth datasets :)

From the spec:
> All the non-Null shapes in a shapefile are required to be of the same shape type.

Currently, since we only read .shp and not yet .dbf, it is not that strange to have `shapes = Vector{jltype}` and to skip null shapes. But perhaps it would be better to instead create `shapes = Vector{Union{jltype, Missing}}` (or `NullShape` instead of `Missing`), and read that instead. If we want to be able to write back shapefiles, we should record this information somehow. What do you think?

**Comment by ndinsmore** [comment]
I don't know what the use case to want to write NullShape back to the file would be.  I guess the only reason would be to preserve numbering of the shapes?  
The Union would be okay but it would make the dispatch for the plotting recipes a little clumsy.

**Comment by visr** [comment]
It's not just to preserve the numbering, it's about losing information. We should be able to read in a shapefile and write it back to get an identical file in most cases. (Though there is no writing implemented yet) And if we gain the ability to read the DBF along with the SHP, we should be able to map records 1:1, a NullShape may have some interesting properties that you are interested in.

I'm not sure it would make the plotting clumsy, though we can check. Either we can define how to plot NullShape (do nothing), or add skipmissing somewhere.
