### ISSUE TITLE
Reading projection .prj

### ISSUE THREAD

**Issue by meggart** [JuliaGeo/Shapefile.jl#31]
It would be nice if one could parse the .prj file as well, which basically contains a WKT string and make it compatible with Geodesy.jl. Is there any work already on a pure Julia WKT parser that does not use LibGEOS or GDAL?

**Comment by visr** [comment]
There is this https://github.com/FugroRoames/RoamesGeometry.jl/blob/master/src/wkt.jl and https://github.com/huaxk/GeoWKB.jl.

**Comment by meggart** [comment]
Thanks, unfortunately both packages don't seem to help, it looks like they decode WKT-encoded geometries, but don't decode the CRS. A typical content of a .prj file looks like this: 

````
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]
````

and it would be great if we could convert this into the correct Geodesy.jl type or throw an error if the coordinate system is currently not supported. As @felixcremer suggested something like this python package would be great https://github.com/karimbahgat/PyCRS

**Comment by visr** [comment]
Yeah indeed. PyCRS looks nice, but probably quite a lot of work, and most of those formats are basically legacy anyway. I'd personally start with the current recommended standard by PROJ, [WKT2](https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems). Though of course for shapefiles you'd probably want ESRI WKT.

You mention LibGEOS and GDAL, and especially the latter is a large dependency. But note that PROJ 6 will cover all needs here. From [RFC73](https://trac.osgeo.org/gdal/wiki/rfc73_proj6_wkt2_srsbarn):
> WKT1, WKT2, ESRI WKT, PROJ strings import and export is now delegated to PROJ. The same holds for import of CRS from the EPSG database, that now relies on proj.db SQLite database.

Is a PROJ dependency also undesirable? Or perhaps you can use SQLite.jl to fish the right information out of proj.db, to cover at least the EPSG database?

**Comment by meggart** [comment]
> Is a PROJ dependency also undesirable? Or perhaps you can use SQLite.jl to fish the right information out of proj.db, to cover at least the EPSG database?

I think this is something we have to decide. As I understood, the intention of the package was to have a pure Julia implementation and if we had GDAL as a dependency to parsethe projection, we could as well use it to read the whole shapefile. 

I will experiment a bit with PROJ. I think it might be a good solution for now that gives us projection string parsing with limited effort.

**Comment by visr** [comment]
For PROJ, you might want to use directly the new API wrapped in https://github.com/JuliaGeo/Proj4.jl/pull/27. The old one is still working, but is deprecated (in the project, not in the julia wrapper yet). Otherwise you'll have to update your code sometime soon.

**Comment by meggart** [comment]
Thanks for the hint. I was already looking at these docs https://proj.org/development/reference/functions.html#transformation-setup and not able to find the function in PROJ4. 

Currently I am still not sure what exactly we would need here. Parsing the WKT using PROJ would make most sense if you want to do further transformations using PROJ so you can easliy transform all your features to desired coordinates. I think it comes down to the question what exactly the `crs` function from GeoInterface expects as a return value. What do other packages return here? The docs just say it should be a Dict, but not what should be in there.

**Comment by visr** [comment]
Which function are you looking for?

The linked PR is not quite finished yet, so it doesn't yet set the path to proj.db on module load. If we do that manually, it works:

```julia
import Proj4

share_proj = joinpath(dirname(dirname(pathof(Proj4))), "deps/usr/share/proj")
Proj4.proj_context_set_search_paths(1, [share_proj])

pj_latlon = Proj4.proj_create("EPSG:4326")

esriwkt = """GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]"""
pj2 = Proj4.proj_create(esriwkt)

print(Proj4.proj_as_wkt(pj2, Proj4.PJ_WKT1_ESRI, C_NULL))
print(Proj4.proj_as_wkt(pj2, Proj4.PJ_WKT2_2018, C_NULL))

```

**Comment by visr** [comment]
> I think it comes down to the question what exactly the `crs` function from GeoInterface expects as a return value. What do other packages return here? The docs just say it should be a Dict, but not what should be in there.

Yeah don't look at this part of the interface too much. The Dict is based on GeoJSON. But the new GeoJSON doesn't even support [support it anymore](https://tools.ietf.org/html/rfc7946#section-4). If we can come up with some good (traits based?) CRS interface that could work with both PROJ and a possible native implementation of a subset thereof, that would be great.

**Comment by rafaqz** [comment]
I put this together as small set of common wrappers for CRS data as `crs` returning a plane `Dict` or string means we cant use dispatch to identify or convert the type. 

https://github.com/rafaqz/CoordinateReferenceSystemsBase.jl/blob/master/src/CoordinateReferenceSystemsBase.jl

The wrappers might not be the most relevent set (its not really my field). But structurally the package makes sense as a dependency for common use cases that rarely do anything with crs metadata, but still need it available. The idea was that actual conversion/manipulatin of crs metadata would happen elsewhere where a Proj4 dep is acceptable (something like https://github.com/rafaqz/CoordinateReferenceSystems.jl)

**Comment by rafaqz** [comment]
How about we check for the .prj file and loading it as a field in `Table` and `Handle`, which will be `nothing` if there is no .prj file?

Then `GeoInterface.crs` can return it. It can be wrapped in `GeoFormatTypes.ProjString`, or not?

**Comment by visr** [comment]
Yeah I think that's a good plan. The .prj file contains the CRS in WKT format however. I'm assuming the ESRI flavor, so `ESRIWellKnownText`, but it would be good to confirm that.
