### ISSUE TITLE
Why is Shapefile.jl mixing `getproperty` with `getfield`?

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [JuliaGeo/Shapefile.jl#55]
This package provides very few builtin documentation and the fact of mixing  `getproperty` with `getfield` does not help to understand how it works.

For example (in table.jl):

```julia
Base.getproperty(t::Table, name::Symbol) = getproperty(getdbf(t), name)
getdbf(t::Table) = getfield(t, :dbf)
```

**Comment by visr** [comment]
So normally if you have a struct `Table`, `t` with field `dbf`, you can normally use `t.dbf` to access this field. This calls [`getproperty`](https://docs.julialang.org/en/v1/base/base/#Base.getproperty), which defaults to `getfield`.

However for https://github.com/JuliaData/Tables.jl you generally want `t.something` to get the column `something` from the table. This is achieved by overloading `getproperty`. However if you now want the field `dbf`, then `t.dbf` no longer works. Now you need to use `getfield` instead.

Does that make it a bit more clear?
