### ISSUE TITLE
EOFError when reading a MultiLineStringZ shapefile

### ISSUE THREAD

**Issue by markmbaum** [JuliaGeo/Shapefile.jl#61]
I used QGIS to drape a vector layer with topographic information. The `Shapefile.Table` function has no issue reading the original file, which has MultiLineString geometry. But it can't read the draped layer, which has MultiLineStringZ geometry. I get the following error message:

```
ERROR: EOFError: read end of file
Stacktrace:
  [1] unsafe_read(s::IOStream, p::Ptr{UInt8}, nb::UInt64)
    @ Base .\iostream.jl:425
  [2] unsafe_read
    @ .\io.jl:722 [inlined]
  [3] read!
    @ .\io.jl:740 [inlined]
  [4] read(io::IOStream, #unused#::Type{Shapefile.PolylineZ})
    @ Shapefile C:\Users\markm\.julia\packages\Shapefile\Vni1U\src\Shapefile.jl:215
  [5] read(io::IOStream, ::Type{Shapefile.Handle}, index::Shapefile.IndexHandle)
    @ Shapefile C:\Users\markm\.julia\packages\Shapefile\Vni1U\src\Shapefile.jl:355
  [6] #1
    @ C:\Users\markm\.julia\packages\Shapefile\Vni1U\src\Shapefile.jl:139 [inlined]
  [7] open(f::Shapefile.var"#1#2"{Shapefile.IndexHandle}, args::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base .\io.jl:330
  [8] open
    @ .\io.jl:328 [inlined]
  [9] Handle
    @ C:\Users\markm\.julia\packages\Shapefile\Vni1U\src\Shapefile.jl:138 [inlined]
 [10] Handle
    @ C:\Users\markm\.julia\packages\Shapefile\Vni1U\src\Shapefile.jl:376 [inlined]
 [11] Shapefile.Table(path::String)
    @ Shapefile C:\Users\markm\.julia\packages\Shapefile\Vni1U\src\table.jl:38
 [12] top-level scope
    @ REPL[9]:1
```

**Comment by markmbaum** [comment]
No problem if the original vector layer is draped into a PolyLineM instead, so that is a workaround.

**Comment by visr** [comment]
Hmm that is strange. MultiLineStringZ is called PolylineZ in shapefiles. It has both M and Z coordinate, so it is 4D.

Checking this function
https://github.com/JuliaGeo/Shapefile.jl/blob/46432ce4cebade3881e61199bb3fe4a4d27bec62/src/Shapefile.jl#L202-L219
with this definition:
https://www.esri.com/Library/Whitepapers/Pdfs/Shapefile.pdf

I don't see a mismatch there. EOFError can happen if it reads the wrong bytes for `numparts` or `numpoints`, and gets a huge number there. Is it possible to debug that function a bit to get a sense of what is going on? There is a PolylineZ example file in the tests that works, so I wonder what the difference is.

**Comment by markmbaum** [comment]
Yes I was looking at some of those test files. I'm not sure where the disagreement is but it's totally possible that the draped file is being written improperly. I'm going to investigate a little, but if I don't find a resolution I'll close the issue anyway.

**Comment by markmbaum** [comment]
It seems like the ESRI standard is for M value to be "optional" in the Z geometries. If you look at Table 14 in the [shapefile description](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf), for example, the M fields are marked as optional. Seems like various packages handle this differently. I'm not sure how Z geometries without M values are written though, whether they have null or absent M values.

Maybe handling optional M values for Z geometries is a feature request, then. I would help if possible.

**Comment by visr** [comment]
Aha, then this is #28 or not? Yes, help would be very welcome!
