### ISSUE TITLE
`coordinates` on `Polygon` duplicates holes

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/Shapefile.jl#65]
I don't totally understand `coordinates(obj::Polygon)`, but it is possible to get duplicated holes in the output - the result of `coordinates` has more points than the original file. 

This seems to be caused by this break from the inner loop that does not break the outer loop:
https://github.com/JuliaGeo/Shapefile.jl/blob/1f52a7dfc789122abd482ac27a15f72fe550fcc9/src/geo_interface.jl#L86-L94

Is this a bug? The result is filling in holes in e.g. rasterization if you don't special-case it.

This seems to fix it:
```julia
    for hole in holes
        found = false
        for i = 1:nrings
            if inring(hole[1], coords[i][1])
                push!(coords[i], hole)
                found = true
                break
            end
        end
        if !found
            push!(coords, Vector{Vector{Float64}}[hole]) # hole is not inside any ring; make it a polygon
        end
    end
```

If that makes sense I'll PR

**Comment by visr** [comment]
Also have a look at the extensive test cases added in #57, that may help.

**Comment by rafaqz** [comment]
What spec do you mean? I'm fine with digging in - but knowing where these details are specified is probably the most important thing here. The test files come from shapelib, but it's not clear where the specification of the `coordinates` output is defined.

The only test that breaks with this change is for `test10.shp`. Its essentially the same shape as `test9.shp`, but `coordinates` outputs is ten points longer, because of the duplication of holes that I'm talking about.

**Comment by rafaqz** [comment]
If I remove the duplication of `coordinates` and apply this change to `PolyggonM` and `PolygonZ` then tests 10-12 all break, as they're identical.

**Comment by visr** [comment]
> it's not clear where the specification of the coordinates output is defined.

The ESRI Shapefile description is here: https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf, but the `GeoInterface.coordinates` function output is structured like GeoJSON, which is here: https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.7. One important thing to note is that a `Shapefile.Polygon` is a `GeoInterface.AbstractMultiPolygon`:

https://github.com/JuliaGeo/Shapefile.jl/blob/1f52a7dfc789122abd482ac27a15f72fe550fcc9/src/Shapefile.jl#L58

Since the Shapefile Polygon allows for multiple exterior rings (in GeoJSON language).

> Why isn't this just a Union type??

No reason I think. It was written 5 years ago and no one touched it since?

**Comment by rafaqz** [comment]
Ok, well we can fix all theses things at the same time.

I cant find anything in the GeoJSON spec that says to duplicate the coordinates for holes.

It seems like @yeesian wrote the original tests that specify this and knows a little more? But yes it seems like that was 7 years ago!

**Comment by rafaqz** [comment]
@yeesian it would be good to have some input here, I cant find anything about needing this duplication, but you are more accross this kind of polygon spec than I am.

**Comment by yeesian** [comment]
Oh yeah it does look like a bug, sorry it took me so long to trace through the discussion. I guess the spec does allow for duplicate holes, so it is valid in that sense, but it is invalid in the sense that it is not an output that we'd expect or want.

**Comment by rafaqz** [comment]
Thanks, I'll remove the duplication and PR
