### ISSUE TITLE
`intersect` is pretty slow

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/Shapefile.jl#67]
During `rasterize` with a shapefile in Rasters.jl, `intersect` in `GeoInterface.coordinates` (the long flat bit) takes more time than all of the point rasterization (which is the bumpy part on the right):

![2022-02-18-173044_2970x2130_scrot](https://user-images.githubusercontent.com/2534009/154723698-495dba08-589d-4528-a49c-6b7e90f6531a.png)

But rasterization doesn't actually need holes in a separate vector, so they just get merged after this. Is there a generic way to get all coordinates from any `AbstractGeometry` without the `intersect` step happening for Shapefile.jl geometries? Otherwise can we make one?

**Comment by visr** [comment]
> But rasterization doesn't actually need holes in a separate vector, so they just get merged after this.

I don't understand this, or what you mean by merging. If your shapefile has holes, why do you want to exclude them during rasterization?

Probably the `coordinates` / `inring` functions can be optimized more in any case. If `inring` would operate on the original Shapefile.Polygon struct it would probably be much faster.

**Comment by rafaqz** [comment]
The holes aren't excluded, they just don't have to be separated for the algorithm to work. It's a line crossing algorithm, so it doesn't matter if a line is for a polygon or hole the result is the same.

It would be best if we can avoid separating them to avoid the overhead. `rasterize` can be really fast in Julia.

**Comment by rafaqz** [comment]
Also using the struct sounds like a good idea.

**Comment by rafaqz** [comment]
Adding a keyword to coordinates easily fixes this (over 2x performance improvement for `rasterize`). But its harder to implement in practice, because it would need to be added in every package that extends GeoInterface.jl. Maybe we could define a new method, even `Base.collect`, to return all the points in any geometry.
 
Probably these things are additions to the updated GeoInterface.jl, or maybe even fixed with in the GeometyBasics.jl PR here, but I don't know where any of these things are at.

**Comment by visr** [comment]
Yeah indeed I don't think adding that keyword argument is the way to go for this. Shapefile polygons are funny in that they are multipolygons with n rings and m holes, in any order. That needs to get sorted out, for GeoInterface, but also for GeometryBasics, which also has a GeoJSON like layout with the outer ring followed by its holes. I think your best bet for accelerating this code without a lot of work (e.g. converting to GeometryBasics or changing the GeoInterface) would be to try to speed up `inring`.

**Comment by rafaqz** [comment]
Ok. I do understand that it needs to be sorted out for polygon applications, and am not suggesting that should change. But a separate interface could avoid that overhead for rasterization where it's not necessary. 

There can be whole minutes spent in `intersect` currently while rasterizing a shapefile. The profile above is for a fraction of the file so that ProfileView.jl can actually display it.

And it seems like GeometryBasics.jl merge might happen? I don't understand where anything of these PRs are at. GB.jl might have a faster `inring` method or similar built in... and I don't really want to do that work just for the short term gain.

And in the long run we need a way of getting raw indexable points from any geometry. Rasterizing huge shapefiles is something I want to do serious performance optimization for in Rasters.jl. It's already at the point where the low hanging fruit is in Shapefiles/GeoInterface - specifically in skipping operations like this, and skipping allocations in `coordinates`. Some kind of view into the raw objects as they are read would be best. If we could index into/iterate over any polygon and its points directly, this would be a non-issue.

**Comment by rafaqz** [comment]
This is not longer a problem as `GeoInterface.getring` can access rings without sorting
